package views;

import storage.DatabaseInterface;
import storage.FileStoreInterface;
import web.WebRequest;
import web.WebResponse;

public class TempLogin extends DynamicWebPage
{

	public TempLogin(DatabaseInterface db,FileStoreInterface fs)
	{
		super(db,fs);
	}

	public boolean process(WebRequest toProcess)
	{
		if(toProcess.path.equalsIgnoreCase("TempLogin.html"))
		{
			String stringToSendToWebBrowser = "";
			stringToSendToWebBrowser += "<html>\n";
			stringToSendToWebBrowser += "  \n";
			stringToSendToWebBrowser += "  <head>\n";
			stringToSendToWebBrowser += "    <meta charset=\"utf-8\">\n";
			stringToSendToWebBrowser += "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
			stringToSendToWebBrowser += "    <script type=\"text/javascript\" src=\"http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js\"></script>\n";
			stringToSendToWebBrowser += "    <script type=\"text/javascript\" src=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js\"></script>\n";
			stringToSendToWebBrowser += "    <link href=\"http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css\"\n";
			stringToSendToWebBrowser += "    rel=\"stylesheet\" type=\"text/css\">\n";
			stringToSendToWebBrowser += "    <link href=\"Login2.css\" rel=\"stylesheet\" type=\"text/css\">\n";
			stringToSendToWebBrowser += "  </head>\n";
			stringToSendToWebBrowser += "  \n";
			stringToSendToWebBrowser += "  <body>\n";
			stringToSendToWebBrowser += "    <div class=\"navbar navbar-default navbar-static-top\">\n";
			stringToSendToWebBrowser += "      <div class=\"container\">\n";
			stringToSendToWebBrowser += "        <div class=\"navbar-header\">\n";
			stringToSendToWebBrowser += "          <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#navbar-ex-collapse\">\n";
			stringToSendToWebBrowser += "            <span class=\"sr-only\">Toggle navigation</span>\n";
			stringToSendToWebBrowser += "            <span class=\"icon-bar\"></span>\n";
			stringToSendToWebBrowser += "            <span class=\"icon-bar\"></span>\n";
			stringToSendToWebBrowser += "            <span class=\"icon-bar\"></span>\n";
			stringToSendToWebBrowser += "          </button>\n";
			stringToSendToWebBrowser += "          <a class=\"navbar-brand\" href=\"#\" contenteditable=\"true\">Hello World</a>\n";
			stringToSendToWebBrowser += "        </div>\n";
			stringToSendToWebBrowser += "        <div class=\"collapse navbar-collapse\" id=\"navbar-ex-collapse\">\n";
			stringToSendToWebBrowser += "          <ul class=\"nav navbar-nav navbar-right\"></ul>\n";
			stringToSendToWebBrowser += "        </div>\n";
			stringToSendToWebBrowser += "      </div>\n";
			stringToSendToWebBrowser += "    </div>\n";
			stringToSendToWebBrowser += "    <div class=\"section\">\n";
			stringToSendToWebBrowser += "      <div class=\"container\">\n";
			stringToSendToWebBrowser += "        <div class=\"row\">\n";
			stringToSendToWebBrowser += "          <div class=\"col-md-12\">\n";
			stringToSendToWebBrowser += "            <ul class=\"breadcrumb\">\n";
			stringToSendToWebBrowser += "              <li>\n";
			stringToSendToWebBrowser += "                <a href=\"#\">Home</a>\n";
			stringToSendToWebBrowser += "              </li>\n";
			stringToSendToWebBrowser += "              <li>\n";
			stringToSendToWebBrowser += "                <a href=\"#\">Trending</a>\n";
			stringToSendToWebBrowser += "              </li>\n";
			stringToSendToWebBrowser += "              <li>\n";
			stringToSendToWebBrowser += "                <a href=\"#\">Languages</a>\n";
			stringToSendToWebBrowser += "              </li>\n";
			stringToSendToWebBrowser += "              <li class=\"active\">Login</li>\n";
			stringToSendToWebBrowser += "              <li>\n";
			stringToSendToWebBrowser += "                <a href=\"#\">Profile</a>\n";
			stringToSendToWebBrowser += "              </li>\n";
			stringToSendToWebBrowser += "              <li>\n";
			stringToSendToWebBrowser += "                <a href=\"#\">Contact Us</a>\n";
			stringToSendToWebBrowser += "              </li>\n";
			stringToSendToWebBrowser += "            </ul>\n";
			stringToSendToWebBrowser += "          </div>\n";
			stringToSendToWebBrowser += "        </div>\n";
			stringToSendToWebBrowser += "        <div class=\"row\">\n";
			stringToSendToWebBrowser += "          <div class=\"col-md-12\">\n";
			stringToSendToWebBrowser += "            <div class=\"page-header text-danger\">\n";
			stringToSendToWebBrowser += "              <h2 class=\"text-primary\">Login</h2>\n";
			stringToSendToWebBrowser += "            </div>\n";
			stringToSendToWebBrowser += "          </div>\n";
			stringToSendToWebBrowser += "        </div>\n";
			stringToSendToWebBrowser += "      </div>\n";
			stringToSendToWebBrowser += "    </div>\n";
			stringToSendToWebBrowser += "    <div class=\"section\">\n";
			stringToSendToWebBrowser += "      <div class=\"container\">\n";
			stringToSendToWebBrowser += "        <div class=\"row\">\n";
			stringToSendToWebBrowser += "          <div class=\"col-md-12\">\n";
			stringToSendToWebBrowser += "            <form class=\"form-horizontal\" role=\"form\">\n";
			stringToSendToWebBrowser += "              <div class=\"form-group has-success\">\n";
			stringToSendToWebBrowser += "                <div class=\"col-sm-2\">\n";
			stringToSendToWebBrowser += "                  <label for=\"inputEmail3\" class=\"control-label\">Email</label>\n";
			stringToSendToWebBrowser += "                </div>\n";
			stringToSendToWebBrowser += "                <div class=\"col-sm-10\">\n";
			stringToSendToWebBrowser += "                  <input type=\"email\" class=\"form-control\" id=\"inputEmail3\" placeholder=\"Email\">\n";
			stringToSendToWebBrowser += "                </div>\n";
			stringToSendToWebBrowser += "              </div>\n";
			stringToSendToWebBrowser += "              <div class=\"form-group has-success\">\n";
			stringToSendToWebBrowser += "                <div class=\"col-sm-2\">\n";
			stringToSendToWebBrowser += "                  <label for=\"inputPassword3\" class=\"control-label\">Password</label>\n";
			stringToSendToWebBrowser += "                </div>\n";
			stringToSendToWebBrowser += "                <div class=\"col-sm-10\">\n";
			stringToSendToWebBrowser += "                  <input type=\"password\" class=\"form-control\" id=\"inputPassword3\" placeholder=\"Password\">\n";
			stringToSendToWebBrowser += "                </div>\n";
			stringToSendToWebBrowser += "              </div>\n";
			stringToSendToWebBrowser += "              <div class=\"form-group\">\n";
			stringToSendToWebBrowser += "                <div class=\"col-sm-offset-2 col-sm-10\">\n";
			stringToSendToWebBrowser += "                  <div class=\"checkbox\">\n";
			stringToSendToWebBrowser += "                    <label>\n";
			stringToSendToWebBrowser += "                      <input type=\"checkbox\">Remember me</label>\n";
			stringToSendToWebBrowser += "                  </div>\n";
			stringToSendToWebBrowser += "                </div>\n";
			stringToSendToWebBrowser += "              </div>\n";
			stringToSendToWebBrowser += "              <div class=\"form-group\">\n";
			stringToSendToWebBrowser += "                <div class=\"col-sm-offset-2 col-sm-10\">\n";
			stringToSendToWebBrowser += "                  <button type=\"submit\" class=\"btn btn-default\">Sign in</button>\n";
			stringToSendToWebBrowser += "                </div>\n";
			stringToSendToWebBrowser += "              </div>\n";
			stringToSendToWebBrowser += "            </form>\n";
			stringToSendToWebBrowser += "          </div>\n";
			stringToSendToWebBrowser += "        </div>\n";
			stringToSendToWebBrowser += "      </div>\n";
			stringToSendToWebBrowser += "    </div>\n";
			stringToSendToWebBrowser += "    <div class=\"section\">\n";
			stringToSendToWebBrowser += "      <div class=\"container-fluid\">\n";
			stringToSendToWebBrowser += "        <div class=\"row text-center\">\n";
			stringToSendToWebBrowser += "          <div class=\"col-md-12 text-center\">\n";
			stringToSendToWebBrowser += "            <hr>\n";
			stringToSendToWebBrowser += "          </div>\n";
			stringToSendToWebBrowser += "        </div>\n";
			stringToSendToWebBrowser += "      </div>\n";
			stringToSendToWebBrowser += "    </div>\n";
			stringToSendToWebBrowser += "    <div class=\"section\">\n";
			stringToSendToWebBrowser += "      <div class=\"container\">\n";
			stringToSendToWebBrowser += "        <div class=\"row\">\n";
			stringToSendToWebBrowser += "          <div class=\"col-md-12\">\n";
			stringToSendToWebBrowser += "            <h2 class=\"text-primary\">Sign up</h2>\n";
			stringToSendToWebBrowser += "          </div>\n";
			stringToSendToWebBrowser += "        </div>\n";
			stringToSendToWebBrowser += "      </div>\n";
			stringToSendToWebBrowser += "    </div>\n";
			stringToSendToWebBrowser += "    <div class=\"section\">\n";
			stringToSendToWebBrowser += "      <div class=\"container\">\n";
			stringToSendToWebBrowser += "        <div class=\"row\">\n";
			stringToSendToWebBrowser += "          <div class=\"col-md-12\">\n";
			stringToSendToWebBrowser += "            <form class=\"form-horizontal\" role=\"form\">\n";
			stringToSendToWebBrowser += "              <div class=\"section\">\n";
			stringToSendToWebBrowser += "                <div class=\"container\">\n";
			stringToSendToWebBrowser += "                  <div class=\"row\">\n";
			stringToSendToWebBrowser += "                    <div class=\"col-md-12\">\n";
			stringToSendToWebBrowser += "                      <div class=\"form-group has-success\">\n";
			stringToSendToWebBrowser += "                        <div class=\"col-sm-2\">\n";
			stringToSendToWebBrowser += "                          <label for=\"inputFirstName\" class=\"control-label\">First Name</label>\n";
			stringToSendToWebBrowser += "                        </div>\n";
			stringToSendToWebBrowser += "                        <div class=\"col-sm-10\">\n";
			stringToSendToWebBrowser += "                          <input type=\"text\" class=\"form-control\" id=\"inputFirstName\" placeholder=\"First Name\">\n";
			stringToSendToWebBrowser += "                        </div>\n";
			stringToSendToWebBrowser += "                      </div>\n";
			stringToSendToWebBrowser += "                      <div class=\"form-group has-success\">\n";
			stringToSendToWebBrowser += "                        <div class=\"col-sm-2\">\n";
			stringToSendToWebBrowser += "                          <label for=\"inputSecondName\" class=\"control-label\">Second Name</label>\n";
			stringToSendToWebBrowser += "                        </div>\n";
			stringToSendToWebBrowser += "                        <div class=\"col-sm-10\">\n";
			stringToSendToWebBrowser += "                          <input type=\"text\" class=\"form-control\" id=\"inputSecondName\" placeholder=\"Second Name\">\n";
			stringToSendToWebBrowser += "                        </div>\n";
			stringToSendToWebBrowser += "                      </div>\n";
			stringToSendToWebBrowser += "                      <div class=\"form-group has-success\">\n";
			stringToSendToWebBrowser += "                        <div class=\"col-sm-2\">\n";
			stringToSendToWebBrowser += "                          <label for=\"inputUsername\" class=\"control-label\">Username</label>\n";
			stringToSendToWebBrowser += "                        </div>\n";
			stringToSendToWebBrowser += "                        <div class=\"col-sm-10\">\n";
			stringToSendToWebBrowser += "                          <input type=\"text\" class=\"form-control\" id=\"inputUsername\" placeholder=\"Enter Username\">\n";
			stringToSendToWebBrowser += "                        </div>\n";
			stringToSendToWebBrowser += "                      </div>\n";
			stringToSendToWebBrowser += "                      <div class=\"form-group has-success\">\n";
			stringToSendToWebBrowser += "                        <div class=\"col-sm-2\">\n";
			stringToSendToWebBrowser += "                          <label for=\"inputEmail3\" class=\"control-label\">Email</label>\n";
			stringToSendToWebBrowser += "                        </div>\n";
			stringToSendToWebBrowser += "                        <div class=\"col-sm-10\">\n";
			stringToSendToWebBrowser += "                          <input type=\"email\" class=\"form-control\" id=\"inputEmail3\" placeholder=\"Email\">\n";
			stringToSendToWebBrowser += "                        </div>\n";
			stringToSendToWebBrowser += "                      </div>\n";
			stringToSendToWebBrowser += "                      <div class=\"form-group has-success\">\n";
			stringToSendToWebBrowser += "                        <div class=\"col-sm-2\">\n";
			stringToSendToWebBrowser += "                          <label for=\"inputPassword3\" class=\"control-label\">Password</label>\n";
			stringToSendToWebBrowser += "                        </div>\n";
			stringToSendToWebBrowser += "                        <div class=\"col-sm-10\">\n";
			stringToSendToWebBrowser += "                          <input type=\"password\" class=\"form-control\" id=\"inputPassword3\" placeholder=\"New Password \">\n";
			stringToSendToWebBrowser += "                        </div>\n";
			stringToSendToWebBrowser += "                      </div>\n";
			stringToSendToWebBrowser += "                      <div class=\"form-group has-success\">\n";
			stringToSendToWebBrowser += "                        <div class=\"col-sm-2\">\n";
			stringToSendToWebBrowser += "                          <label for=\"inputPassword4\" class=\"control-label\">Password</label>\n";
			stringToSendToWebBrowser += "                        </div>\n";
			stringToSendToWebBrowser += "                        <div class=\"col-sm-10\">\n";
			stringToSendToWebBrowser += "                          <input type=\"password\" class=\"form-control\" id=\"inputPassword4\" placeholder=\"Re-enter password\">\n";
			stringToSendToWebBrowser += "                        </div>\n";
			stringToSendToWebBrowser += "                      </div>\n";
			stringToSendToWebBrowser += "                      <div class=\"form-group\"></div>\n";
			stringToSendToWebBrowser += "                      <div class=\"form-group has-success\">\n";
			stringToSendToWebBrowser += "                        <div class=\"col-sm-2\">\n";
			stringToSendToWebBrowser += "                          <label for=\"inputCountry\" class=\"control-label\">Country of Residence</label>\n";
			stringToSendToWebBrowser += "                        </div>\n";
			stringToSendToWebBrowser += "                        <div class=\"col-sm-10\">\n";
			stringToSendToWebBrowser += "                          <a class=\"btn btn-primary dropdown-toggle\" data-toggle=\"dropdown\"> Country <span class=\"fa fa-caret-down\"></span></a>\n";
			stringToSendToWebBrowser += "                          <ul class=\"dropdown-menu\" role=\"menu\">\n";
			stringToSendToWebBrowser += "                            <li>\n";
			stringToSendToWebBrowser += "                              <a href=\"United Kingdom\">United Kingdom</a>\n";
			stringToSendToWebBrowser += "                            </li>\n";
			stringToSendToWebBrowser += "                            <li>\n";
			stringToSendToWebBrowser += "                              <a href=\"Ireland\">Ireland</a>\n";
			stringToSendToWebBrowser += "                            </li>\n";
			stringToSendToWebBrowser += "                            <li>\n";
			stringToSendToWebBrowser += "                              <a href=\"Spain\"> Spain</a>\n";
			stringToSendToWebBrowser += "                            </li>\n";
			stringToSendToWebBrowser += "                            <li>\n";
			stringToSendToWebBrowser += "                              <a href=\"France\"> France</a>\n";
			stringToSendToWebBrowser += "                            </li>\n";
			stringToSendToWebBrowser += "                            <li>\n";
			stringToSendToWebBrowser += "                              <a href=\"Poland\"> Poland</a>\n";
			stringToSendToWebBrowser += "                            </li>\n";
			stringToSendToWebBrowser += "                            <li>\n";
			stringToSendToWebBrowser += "                              <a href=\"Italy\"> Italy</a>\n";
			stringToSendToWebBrowser += "                            </li>\n";
			stringToSendToWebBrowser += "                            <li>\n";
			stringToSendToWebBrowser += "                              <a href=\"Germany\"> Germany</a>\n";
			stringToSendToWebBrowser += "                            </li>\n";
			stringToSendToWebBrowser += "                            <li>\n";
			stringToSendToWebBrowser += "                              <a href=\"Turkey\"> Turkey</a>\n";
			stringToSendToWebBrowser += "                            </li>\n";
			stringToSendToWebBrowser += "                            <li>\n";
			stringToSendToWebBrowser += "                              <a href=\"Portugal\"> Portugal</a>\n";
			stringToSendToWebBrowser += "                            </li>\n";
			stringToSendToWebBrowser += "                            <li>\n";
			stringToSendToWebBrowser += "                              <a href=\"Sweden\"> Sweden</a>\n";
			stringToSendToWebBrowser += "                            </li>\n";
			stringToSendToWebBrowser += "                            <li>\n";
			stringToSendToWebBrowser += "                              <a href=\"Denmark\"> Denmark</a>\n";
			stringToSendToWebBrowser += "                            </li>\n";
			stringToSendToWebBrowser += "                            <li>\n";
			stringToSendToWebBrowser += "                              <a href=\"Norway\"> Norway</a>\n";
			stringToSendToWebBrowser += "                            </li>\n";
			stringToSendToWebBrowser += "                            <li>\n";
			stringToSendToWebBrowser += "                              <a href=\"Canada\"> Canada</a>\n";
			stringToSendToWebBrowser += "                            </li>\n";
			stringToSendToWebBrowser += "                            <li>\n";
			stringToSendToWebBrowser += "                              <a href=\"North America\"> North America</a>\n";
			stringToSendToWebBrowser += "                            </li>\n";
			stringToSendToWebBrowser += "                            <li>\n";
			stringToSendToWebBrowser += "                              <a href=\"South America\"> South America</a>\n";
			stringToSendToWebBrowser += "                            </li>\n";
			stringToSendToWebBrowser += "                            <li>\n";
			stringToSendToWebBrowser += "                              <a href=\"AustraliaNZ\"> Australia/New Zealand</a>\n";
			stringToSendToWebBrowser += "                            </li>\n";
			stringToSendToWebBrowser += "                          </ul>\n";
			stringToSendToWebBrowser += "                        </div>\n";
			stringToSendToWebBrowser += "                      </div>\n";
			stringToSendToWebBrowser += "                    </div>\n";
			stringToSendToWebBrowser += "                  </div>\n";
			stringToSendToWebBrowser += "                  <div class=\"form-group has-success\">\n";
			stringToSendToWebBrowser += "                    <div class=\"col-sm-2\">\n";
			stringToSendToWebBrowser += "                      <label for=\"inputEducation\" class=\"control-label\">Education Level</label>\n";
			stringToSendToWebBrowser += "                    </div>\n";
			stringToSendToWebBrowser += "                    <div class=\"col-sm-10\">\n";
			stringToSendToWebBrowser += "                      <a class=\"btn btn-primary dropdown-toggle\" data-toggle=\"dropdown\"> Education <span class=\"fa fa-caret-down\"></span></a>\n";
			stringToSendToWebBrowser += "                      <ul class=\"dropdown-menu\" role=\"menu\">\n";
			stringToSendToWebBrowser += "                        <li>\n";
			stringToSendToWebBrowser += "                          <a href=\"GSCE\">GCSE</a>\n";
			stringToSendToWebBrowser += "                        </li>\n";
			stringToSendToWebBrowser += "                        <li>\n";
			stringToSendToWebBrowser += "                          <a href=\"A Level\">A Level</a>\n";
			stringToSendToWebBrowser += "                        </li>\n";
			stringToSendToWebBrowser += "                        <li>\n";
			stringToSendToWebBrowser += "                          <a href=\"University\"> University</a>\n";
			stringToSendToWebBrowser += "                        </li>\n";
			stringToSendToWebBrowser += "                      </ul>\n";
			stringToSendToWebBrowser += "                    </div>\n";
			stringToSendToWebBrowser += "                  </div>\n";
			stringToSendToWebBrowser += "                  <div class=\"btn-group btn-group-sm\"></div>\n";
			stringToSendToWebBrowser += "                  <div class=\"form-group has-success\">\n";
			stringToSendToWebBrowser += "                    <div class=\"col-sm-2\">\n";
			stringToSendToWebBrowser += "                      <label for=\"inputGender\" class=\"control-label\">Gender</label>\n";
			stringToSendToWebBrowser += "                    </div>\n";
			stringToSendToWebBrowser += "                    <div class=\"col-sm-10\">\n";
			stringToSendToWebBrowser += "                      <input type=\"checkbox\" name=\"gender\" value=\"Male\">Male\n";
			stringToSendToWebBrowser += "                      <br>\n";
			stringToSendToWebBrowser += "                      <input type=\"checkbox\" name=\"gender\" value=\"Female\">Female\n";
			stringToSendToWebBrowser += "                      <br>\n";
			stringToSendToWebBrowser += "                    </div>\n";
			stringToSendToWebBrowser += "                  </div>\n";
			stringToSendToWebBrowser += "                  <div class=\"form-group\"></div>\n";
			stringToSendToWebBrowser += "                </div>\n";
			stringToSendToWebBrowser += "              </div>\n";
			stringToSendToWebBrowser += "              <input type=\"checkbox\" name=\"subcribe\" value=\"Agree\">I agree to the terms and conditions\n";
			stringToSendToWebBrowser += "              <br>\n";
			stringToSendToWebBrowser += "              <input type=\"checkbox\" name=\"subcribe\" value=\"subcribtion\" checked=\"\">I want to recieve the weekly newsletter\n";
			stringToSendToWebBrowser += "              <br>\n";
			stringToSendToWebBrowser += "            </form>\n";
			stringToSendToWebBrowser += "          </div>\n";
			stringToSendToWebBrowser += "        </div>\n";
			stringToSendToWebBrowser += "        <div class=\"form-group\">\n";
			stringToSendToWebBrowser += "          <div class=\"col-sm-offset-2 col-sm-10\">\n";
			stringToSendToWebBrowser += "            <button type=\"submit\" class=\"btn btn-default\">Submit</button>\n";
			stringToSendToWebBrowser += "          </div>\n";
			stringToSendToWebBrowser += "        </div>\n";
			stringToSendToWebBrowser += "      </div>\n";
			stringToSendToWebBrowser += "    </div>\n";
			stringToSendToWebBrowser += "  </body>\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "</html>\n";
			toProcess.r = new WebResponse( WebResponse.HTTP_OK, WebResponse.MIME_HTML, stringToSendToWebBrowser );
			return true;
		}
		return false;
	}

}
